### ISSUE TITLE
Option to disable table of contents

### ISSUE THREAD

**Issue by spacedawwwg** [andrewbrandwood/gulp-sass-generate-contents#4]
It would be nice to be able to disable the table of contents in the top of the file.

I use a tool called styledown that generates a file based on comments in the CSS. It is trying to use the table of contents comment block, which is causing issues.

an option like `contentsList: true/false` would be a nice feature

**Comment by spacedawwwg** [comment]
Added in pull request: https://github.com/andrewbrandwood/gulp-sass-generate-contents/pull/5

**Comment by andrewbrandwood** [comment]
merged and release as version 0.3.1 to npm
