### ISSUE TITLE
Don't Overwrite file

### ISSUE THREAD

**Issue by prosenjit-itobuz** [andrewbrandwood/gulp-sass-generate-contents#7]
Don't Overwrite file. It causes error. I want to manage my own component ordering and dependency. Please put just the table of contents.

So you may add an optional attribute, don't replace file only prepend table of content in selected scss file.

**Comment by andrewbrandwood** [comment]
You can manage your own ordering in the setup of the task.  The array passed in is the order the task will generate the contents file.

`gulp.task('gulp-sass-generate-contents', function () {
    gulp.src([
       'sass/**/*.scss',
       'partials/**/*.scss',
       'your-file-order.scss',
       'your-file-order-2.scss'
     ])
    .pipe(gsgc('css/main.scss', creds))
    .pipe(gulp.dest('css'));
});`
